# Generated by Django 3.0.6 on 2020-06-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
